task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 35 # classes + 1
remap_mscoco_category: False # custom dataset -> False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./tools/dataset/wholebody34/images/
    ann_file: ./tools/dataset/wholebody34/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./tools/dataset/wholebody34/images/
    ann_file: ./tools/dataset/wholebody34/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction