__include__: [
  '../dataset/wholebody34.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml'
]

output_dir: ./outputs/deimv2_hgnetv2_n_wholebody34

HGNetv2:
  name: 'B0'
  return_idx: [2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

HybridEncoder:
  in_channels: [512, 1024]
  feat_strides: [16, 32]

  # intra
  hidden_dim: 128
  use_encoder_idx: [1]
  dim_feedforward: 512

  # cross
  expansion: 0.34
  depth_mult: 0.5

  version: 'dfine'

DEIMTransformer:
  feat_channels: [128, 128]
  feat_strides: [16, 32]
  hidden_dim: 128
  num_levels: 2
  num_points: [6, 6]

  num_layers: 3
  eval_idx: -1
  num_queries: 680

  # FFN
  dim_feedforward: 512

PostProcessor:
  num_top_queries: 680

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002 # 0.0008 / 4 * GPUs
  betas: [0.9, 0.999]
  weight_decay: 0.000025 # 0.0001 / 4 * GPUs

# Increase to search for the optimal ema
epoches: 64 # 148 + 12

## Our LR-Scheduler
flat_epoch: 40    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 12
lr_gamma: 1.0

## Our DataAug
train_dataloader:
  dataset:
    transforms:
      ops:
        # - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
        #    probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, p: 0.5, fill: 0, side_range: [1.0, 1.5]}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 2}
        # right-front <-> left-front
        # right-side <-> left-side
        # right-back <-> left-back
        # hand_left <-> hand_right
        - {type: RandomHorizontalFlipWithClass, class_pairs: [[9, 15], [10, 14], [11, 13], [27, 28]]}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 2}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        # The policy block configures the staged augmentation scheduler used by engine/data/transforms/container.py:57. The loader wraps your ops in Compose, and policy['name'] selects which scheduling routine to run (default, stop_epoch, or stop_sample).
        # In DEIM configs we rely on stop_epoch (see engine/data/transforms/container.py:77). The dataloader calls set_epoch, so every batch knows the current epoch and the policy can enable/disable transforms dynamically.
        # Fields for stop_epoch
        # ops: list of transform class names that the scheduler is allowed to turn on/off (e.g. ['Mosaic', 'RandomPhotometricDistort', ...]). Names must match the actual class names printed when transforms are created.
        # epoch: either
        # a single integer → once dataset.epoch >= epoch, transforms listed in ops are skipped; or
        # a list with three values [no_aug_end, mosaic_end, full_stop] → implements a four-stage schedule (engine/data/transforms/container.py:90).
        # epoch < no_aug_end: skip all listed ops (pure warmup).
        # no_aug_end ≤ epoch < mosaic_end: apply listed ops, but Mosaic only fires with mosaic_prob and RandomZoomOut / RandomIoUCrop are suppressed when Mosaic already ran.
        # mosaic_end ≤ epoch < full_stop: listed ops run every time (no Mosaic special-casing).
        # epoch ≥ full_stop: listed ops are skipped again for the final no‑augmentation phase.
        epoch: [4, 40, 52]   # list
        ops: ['Mosaic', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
      mosaic_prob: -0.1
  total_batch_size: 4 # total batch size equals to 32 (4 GPUs * 8 batch)
  num_workers: 4

  collate_fn:
    ema_restart_decay: 0.9999
    base_size_repeat: ~
    mixup_prob: 0.0
    mixup_epochs: [4, 78]
    stop_epoch: 148
    copyblend_prob: 0.0
    copyblend_epochs: [4, 78]   # CP half
    area_threshold: 100
    num_objects: 3
    with_expand: True
    expand_ratios: [0.1, 0.25]

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  total_batch_size: 16 # total batch size equals to 64 (4 GPUs * 16 batch)
  num_workers: 4

DEIMCriterion:
  matcher:
    # new matcher
    change_matcher: True
    iou_order_alpha: 4.0
    matcher_change_epoch: 52